# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - deletemeapp24324

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fd394f215f7042b999a57c3e80801609 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_60bd2d2dbbd84fdd869209196f27d752 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd394f215f7042b999a57c3e80801609 }}/delete:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deletemeapp24324'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd618cf2ddb542afa38eb9d4527b0dd3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fd394f215f7042b999a57c3e80801609 }}/delete:${{ github.sha }}'