# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - story31

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d35e96d2be0f445baacfd1c1ac7c698e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3c0e5dacb4714465b7f4c794f572f2a1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d35e96d2be0f445baacfd1c1ac7c698e }}/storiesoftheland:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'story31'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3cfdb2f9dcdd40a59068529482082e7a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d35e96d2be0f445baacfd1c1ac7c698e }}/storiesoftheland:${{ github.sha }}'