# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - storytest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6549e81511f43aebc83c8bfe25afa47 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a2030819d92a418a932b4458a2f6e274 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6549e81511f43aebc83c8bfe25afa47 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'storytest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c6dbf71c60d4d6b912c312047b65791 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6549e81511f43aebc83c8bfe25afa47 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'