# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - storytest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b120197dd292440e9cfd45da9c451483 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63cc8c14c77a4538b4bed11d8a0e3286 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b120197dd292440e9cfd45da9c451483 }}/storyimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'storytest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e9f542678294ca38f84106c4df99f19 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b120197dd292440e9cfd45da9c451483 }}/storyimage:${{ github.sha }}'